### ISSUE TITLE
Failing to load UI due to JavaScript module loading error

### ISSUE THREAD

**Issue by auroraanna** [gitmh/FLACI#1]
Whether I use electron-packager or just use the source code folder to point the electron executable, I get this error in the browser console:
```console
angular.js:68 Uncaught Error: [$injector:modulerr] Failed to instantiate module App due to:
Error: [$injector:modulerr] Failed to instantiate module as.sortable due to:
Error: [$injector:nomod] Module 'as.sortable' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.4.5/$injector/nomod?p0=as.sortable
    at file:///nix/store/aqs16ja2iip6785qrza8791s6zhnnrqg-flaci-19.0.2/share/flaci/libs/angular/angular.js:68:12
    at file:///nix/store/aqs16ja2iip6785qrza8791s6zhnnrqg-flaci-19.0.2/share/flaci/libs/angular/angular.js:1983:17
    at ensure (file:///nix/store/aqs16ja2iip6785qrza8791s6zhnnrqg-flaci-19.0.2/share/flaci/libs/angular/angular.js:1907:38)
    at module (file:///nix/store/aqs16ja2iip6785qrza8791s6zhnnrqg-flaci-19.0.2/share/flaci/libs/angular/angular.js:1981:14)
    at file:///nix/store/aqs16ja2iip6785qrza8791s6zhnnrqg-flaci-19.0.2/share/flaci/libs/angular/angular.js:4385:22
    at forEach (file:///nix/store/aqs16ja2iip6785qrza8791s6zhnnrqg-flaci-19.0.2/share/flaci/libs/angular/angular.js:336:20)
    at loadModules (file:///nix/store/aqs16ja2iip6785qrza8791s6zhnnrqg-flaci-19.0.2/share/flaci/libs/angular/angular.js:4369:5)
    at file:///nix/store/aqs16ja2iip6785qrza8791s6zhnnrqg-flaci-19.0.2/share/flaci/libs/angular/angular.js:4386:40
    at forEach (file:///nix/store/aqs16ja2iip6785qrza8791s6zhnnrqg-flaci-19.0.2/share/flaci/libs/angular/angular.js:336:20)
    at loadModules (file:///nix/store/aqs16ja2iip6785qrza8791s6zhnnrqg-flaci-19.0.2/share/flaci/libs/angular/angular.js:4369:5)
http://errors.angularjs.org/1.4.5/$injector/modulerr?p0=as.sortable&p1=Error%3A%20%5B%24injector%3Anomod%5D%20Module%20'as.sortable'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.4.5%2F%24injector%2Fnomod%3Fp0%3Das.sortable%0A%20%20%20%20at%20file%3A%2F%2F%2Fnix%2Fstore%2Faqs16ja2iip6785qrza8791s6zhnnrqg-flaci-19.0.2%2Fshare%2Fflaci%2Flibs%2Fangular%2Fangular.js%3A68%3A12%0A%20%20%20%20at%20file%3A%2F%2F%2Fnix%2Fstore%2Faqs16ja2iip6785qrza8791s6zhnnrqg-flaci-19.0.2%2Fshare%2Fflaci%2Flibs%2Fangular%2Fangular.js%3A1983%3A17%0A%20%20%20%20at%20ensure%20(file%3A%2F%2F%2Fnix%2Fstore%2Faqs16ja2iip6785qrza8791s6zhnnrqg-flaci-19.0.2%2Fshare%2Fflaci%2Flibs%2Fangular%2Fangular.js%3A1907%3A38)%0A%20%20%20%20at%20module%20(file%3A%2F%2F%2Fnix%2Fstore%2Faqs16ja2iip6785qrza8791s6zhnnrqg-flaci-19.0.2%2Fshare%2Fflaci%2Flibs%2Fangular%2Fangular.js%3A1981%3A14)%0A%20%20%20%20at%20file%3A%2F%2F%2Fnix%2Fstore%2Faqs16ja2iip6785qrza8791s6zhnnrqg-flaci-19.0.2%2Fshare%2Fflaci%2Flibs%2Fangular%2Fangular.js%3A4385%3A22%0A%20%20%20%20at%20forEach%20(file%3A%2F%2F%2Fnix%2Fstore%2Faqs16ja2iip6785qrza8791s6zhnnrqg-flaci-19.0.2%2Fshare%2Fflaci%2Flibs%2Fangular%2Fangular.js%3A336%3A20)%0A%20%20%20%20at%20loadModules%20(file%3A%2F%2F%2Fnix%2Fstore%2Faqs16ja2iip6785qrza8791s6zhnnrqg-flaci-19.0.2%2Fshare%2Fflaci%2Flibs%2Fangular%2Fangular.js%3A4369%3A5)%0A%20%20%20%20at%20file%3A%2F%2F%2Fnix%2Fstore%2Faqs16ja2iip6785qrza8791s6zhnnrqg-flaci-19.0.2%2Fshare%2Fflaci%2Flibs%2Fangular%2Fangular.js%3A4386%3A40%0A%20%20%20%20at%20forEach%20(file%3A%2F%2F%2Fnix%2Fstore%2Faqs16ja2iip6785qrza8791s6zhnnrqg-flaci-19.0.2%2Fshare%2Fflaci%2Flibs%2Fangular%2Fangular.js%3A336%3A20)%0A%20%20%20%20at%20loadModules%20(file%3A%2F%2F%2Fnix%2Fstore%2Faqs16ja2iip6785qrza8791s6zhnnrqg-flaci-19.0.2%2Fshare%2Fflaci%2Flibs%2Fangular%2Fangular.js%3A4369%3A5)
    at file:///nix/store/aqs16ja2iip6785qrza8791s6zhnnrqg-flaci-19.0.2/share/flaci/libs/angular/angular.js:68:12
    at file:///nix/store/aqs16ja2iip6785qrza8791s6zhnnrqg-flaci-19.0.2/share/flaci/libs/angular/angular.js:4408:15
    at forEach (file:///nix/store/aqs16ja2iip6785qrza8791s6zhnnrqg-flaci-19.0.2/share/flaci/libs/angular/angular.js:336:20)
    at loadModules (file:///nix/store/aqs16ja2iip6785qrza8791s6zhnnrqg-flaci-19.0.2/share/flaci/libs/angular/angular.js:4369:5)
    at file:///nix/store/aqs16ja2iip6785qrza8791s6zhnnrqg-flaci-19.0.2/share/flaci/libs/angular/angular.js:4386:40
    at forEach (file:///nix/store/aqs16ja2iip6785qrza8791s6zhnnrqg-flaci-19.0.2/share/flaci/libs/angular/angular.js:336:20)
    at loadModules (file:///nix/store/aqs16ja2iip6785qrza8791s6zhnnrqg-flaci-19.0.2/share/flaci/libs/angular/angular.js:4369:5)
    at createInjector (file:///nix/store/aqs16ja2iip6785qrza8791s6zhnnrqg-flaci-19.0.2/share/flaci/libs/angular/angular.js:4294:11)
    at doBootstrap (file:///nix/store/aqs16ja2iip6785qrza8791s6zhnnrqg-flaci-19.0.2/share/flaci/libs/angular/angular.js:1655:20)
    at bootstrap (file:///nix/store/aqs16ja2iip6785qrza8791s6zhnnrqg-flaci-19.0.2/share/flaci/libs/angular/angular.js:1676:12)
http://errors.angularjs.org/1.4.5/$injector/modulerr?p0=App&p1=Error%3A%20%5B%24injector
(anonymous) @ angular.js:68
(anonymous) @ angular.js:4408
forEach @ angular.js:336
loadModules @ angular.js:4369
createInjector @ angular.js:4294
doBootstrap @ angular.js:1655
bootstrap @ angular.js:1676
angularInit @ angular.js:1570
(anonymous) @ angular.js:28683
j @ jquery-2.1.1.min.js:2
fireWith @ jquery-2.1.1.min.js:2
ready @ jquery-2.1.1.min.js:2
I @ jquery-2.1.1.min.js:2
```
This error due not occur when pointing electron to the `resources/app` of the provided Linux download.

**Comment by gitmh** [comment]
I just added a package json for npm for the node_modules. Please find the instruction in the readme.

**Comment by auroraanna** [comment]
It is the same instruction I already used. The error is still there.

**Comment by auroraanna** [comment]
Also, there was another error I could fix though. electron-packager does does not produce `FLACI-linux-x64/resources/app/libs/ng-sortable/dist` just `FLACI-linux-x64/resources/app/libs/ng-sortable/distOld` but the former is needed. I can just rename the folder but that seems a bit sketchy.

**Comment by gitmh** [comment]
Strange, I just delete this old and unused distOld folder. Used a Mac to create the apps with electron-packager and they get generated fine - no idea why the packager should not add the /dist folder you mentioned. Maybe there will be other files missing too? In theory the whole folder should be in FLACI-linux-x64/resources/app/ after packing.

**Comment by auroraanna** [comment]
well, now there's no `dist*` folder at all in `libs/ng-sortable/`

**Comment by gitmh** [comment]
Thank you for your feedback. The predefined .gitignore from Github removed all /dist folders. The files are now in the repository.

**Comment by auroraanna** [comment]
nice, got it working now
